version: "3.3"

services:
  wordpress:
    image: wordpress:php7.2-apache
    depends_on:
      - mysql
    ports:
      - 8081:80
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: B47m4n03
      WORDPRESS_DB_NAME: wordpress
    links:
      - mysql:mysql


  mysql:
    image: mysql:8.0.13
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_ROOT_PASSWORD: B47m4n03
    # volumes:
    #   - ~/Documents/pro/docker/mysql-data:/var/lib/mysql